# Generated by Django 4.1.4 on 2022-12-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authentication_token',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='authentication_token'),
        ),
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='device_id'),
        ),
        migrations.AddField(
            model_name='user',
            name='game_access_token',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='game_access_token'),
        ),
        migrations.AddField(
            model_name='user',
            name='next_event',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='next_event'),
        ),
        migrations.AddField(
            model_name='user',
            name='player_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='player id'),
        ),
        migrations.AddField(
            model_name='user',
            name='remember_me_token',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='authentication_token'),
        ),
        migrations.AddField(
            model_name='user',
            name='support_url',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='support_url'),
        ),
    ]
