# Generated by Django 4.1.4 on 2023-01-20 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerwhistleitem',
            name='article',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.tsarticle'),
        ),
        migrations.AddField(
            model_name='playerwhistleitem',
            name='player_whistle',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='players.playerwhistle'),
        ),
        migrations.AddField(
            model_name='playerwhistleitem',
            name='version',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.runversion'),
        ),
        migrations.AddField(
            model_name='playerwhistle',
            name='version',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.runversion'),
        ),
        migrations.AddField(
            model_name='playerwarehouse',
            name='article',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.tsarticle'),
        ),
        migrations.AddField(
            model_name='playerwarehouse',
            name='version',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.runversion'),
        ),
        migrations.AddField(
            model_name='playertrain',
            name='load',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.tsarticle'),
        ),
        migrations.AddField(
            model_name='playertrain',
            name='train',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.tstrain'),
        ),
        migrations.AddField(
            model_name='playertrain',
            name='version',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.runversion'),
        ),
        migrations.AddField(
            model_name='playerleaderboardprogress',
            name='leader_board',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='players.playerleaderboard'),
        ),
        migrations.AddField(
            model_name='playerleaderboardprogress',
            name='version',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.runversion'),
        ),
        migrations.AddField(
            model_name='playerleaderboard',
            name='player_job',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='players.playerjob'),
        ),
        migrations.AddField(
            model_name='playerleaderboard',
            name='version',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.runversion'),
        ),
        migrations.AddField(
            model_name='playerjob',
            name='job_location',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.tsjoblocation'),
        ),
        migrations.AddField(
            model_name='playerjob',
            name='required_article',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.tsarticle'),
        ),
        migrations.AddField(
            model_name='playerjob',
            name='version',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.runversion'),
        ),
        migrations.AddField(
            model_name='playergift',
            name='version',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.runversion'),
        ),
        migrations.AddField(
            model_name='playerfactoryproductorder',
            name='article',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.tsarticle'),
        ),
        migrations.AddField(
            model_name='playerfactoryproductorder',
            name='player_factory',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='players.playerfactory'),
        ),
        migrations.AddField(
            model_name='playerfactoryproductorder',
            name='version',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.runversion'),
        ),
        migrations.AddField(
            model_name='playerfactory',
            name='factory',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.tsfactory'),
        ),
        migrations.AddField(
            model_name='playerfactory',
            name='version',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.runversion'),
        ),
        migrations.AddField(
            model_name='playerdestination',
            name='definition',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.tsdestination'),
        ),
        migrations.AddField(
            model_name='playerdestination',
            name='location',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.tslocation'),
        ),
        migrations.AddField(
            model_name='playerdestination',
            name='version',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.runversion'),
        ),
        migrations.AddField(
            model_name='playercontractlist',
            name='version',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.runversion'),
        ),
        migrations.AddField(
            model_name='playercontract',
            name='contract_list',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='players.playercontractlist'),
        ),
        migrations.AddField(
            model_name='playercontract',
            name='version',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.runversion'),
        ),
        migrations.AddField(
            model_name='playerbuilding',
            name='version',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.runversion'),
        ),
    ]
