# Generated by Django 4.1.4 on 2023-01-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tstrain',
            name='era',
            field=models.IntegerField(choices=[(1, '스팀'), (2, '전기'), (3, '디젤')], default=0, verbose_name='era'),
        ),
    ]
