# Generated by Django 4.1.4 on 2022-12-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created date')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='modified date')),
                ('version', models.CharField(max_length=20, verbose_name='version')),
                ('checksum', models.CharField(max_length=50, verbose_name='checksum')),
                ('url', models.URLField(verbose_name='download url')),
                ('download_path', models.CharField(max_length=200, verbose_name='checksum')),
            ],
            options={
                'verbose_name': 'Definition',
                'verbose_name_plural': 'Definitions',
            },
        ),
    ]
