# Generated by Django 4.1.4 on 2022-12-30 15:48

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created date')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='modified date')),
                ('level_req', models.IntegerField(default=0, verbose_name='level required')),
                ('level_from', models.IntegerField(default=0, verbose_name='level from')),
                ('type', models.IntegerField(default=0, verbose_name='type')),
                ('event', models.IntegerField(default=0, verbose_name='event')),
                ('content_category', models.IntegerField(default=0, verbose_name='content category')),
                ('sprite', models.CharField(max_length=255, null=True, verbose_name='sprite id')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created date')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='modified date')),
                ('version', models.CharField(max_length=20, verbose_name='version')),
                ('checksum', models.CharField(max_length=50, verbose_name='checksum')),
                ('url', models.URLField(verbose_name='download url')),
                ('download_path', models.CharField(max_length=200, verbose_name='checksum')),
            ],
            options={
                'verbose_name': 'Definition',
                'verbose_name_plural': 'Definitions',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created date')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='modified date')),
                ('level_req', models.IntegerField(default=0, verbose_name='level required')),
                ('level_from', models.IntegerField(default=0, verbose_name='level from')),
                ('starting_slot_count', models.IntegerField(default=0, verbose_name='starting_slot_count')),
                ('max_slot_count', models.IntegerField(default=0, verbose_name='max_slot_count')),
                ('type', models.IntegerField(default=0, verbose_name='type')),
                ('content_category', models.IntegerField(default=0, verbose_name='content category')),
                ('asset_name', models.CharField(max_length=255, verbose_name='asset_name')),
                ('sprite', models.CharField(max_length=255, verbose_name='sprite id')),
            ],
            options={
                'verbose_name': 'Factory',
                'verbose_name_plural': 'Factories',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created date')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='modified date')),
                ('region', models.IntegerField(default=0, verbose_name='region')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='PlayerFactory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created date')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='modified date')),
                ('slot_count', models.IntegerField(verbose_name='slot count')),
                ('factory', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bot.factory')),
            ],
            options={
                'verbose_name': 'Player Factory',
                'verbose_name_plural': 'Player Factories',
            },
        ),
        migrations.CreateModel(
            name='PlayerJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created date')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='modified date')),
                ('job_id', models.CharField(max_length=100, verbose_name='job id')),
                ('job_level', models.IntegerField(default=0, verbose_name='CraftTime')),
                ('sequence', models.IntegerField(default=0, verbose_name='Sequence')),
                ('job_type', models.IntegerField(default=0, verbose_name='JobType')),
                ('duration', models.IntegerField(default=0, verbose_name='Duration')),
                ('condition_multiplier', models.IntegerField(default=0, verbose_name='ConditionMultiplier')),
                ('reward_multiplier', models.IntegerField(default=0, verbose_name='RewardMultiplier')),
                ('current_article_amount', models.IntegerField(default=0, verbose_name='CurrentArticleAmount')),
                ('unlock_at', models.DateTimeField(default=None, null=True, verbose_name='UnlocksAt')),
            ],
            options={
                'verbose_name': 'Player Job',
                'verbose_name_plural': 'Player Jobs',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created date')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='modified date')),
                ('level_from', models.IntegerField(default=0, verbose_name='level from')),
                ('content_category', models.IntegerField(default=0, verbose_name='content category')),
                ('asset_name', models.CharField(max_length=255, verbose_name='sprite id')),
                ('gold_amount_coefficient', models.IntegerField(default=0, verbose_name='gold_amount_coefficient')),
                ('train_upgrade_price_coefficient', models.DecimalField(blank=True, decimal_places=10, default=Decimal('0.0'), max_digits=30, verbose_name='train_upgrade_price_coefficient')),
                ('city_currency_coefficient', models.IntegerField(default=0, verbose_name='city_currency_coefficient')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created date')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='modified date')),
                ('content_category', models.IntegerField(default=0, verbose_name='content_category')),
                ('reward', models.BooleanField(default=False, verbose_name='reward')),
                ('region', models.IntegerField(default=0, verbose_name='region')),
                ('rarity', models.IntegerField(default=0, verbose_name='rarity')),
                ('max_level', models.IntegerField(default=0, verbose_name='max_level')),
                ('era', models.IntegerField(default=0, verbose_name='era')),
                ('asset_name', models.CharField(max_length=255, verbose_name='asset_name')),
            ],
            options={
                'verbose_name': 'Train',
                'verbose_name_plural': 'Trains',
            },
        ),
        migrations.CreateModel(
            name='RunVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created date')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='modified date')),
                ('task_status', models.PositiveSmallIntegerField(choices=[(10, 'in queued'), (20, 'in processing'), (30, 'error'), (40, 'completed')], default=10, verbose_name='status of crawling task')),
                ('queued_datetime', models.DateTimeField(blank=True, default=None, null=True, verbose_name='queued datetime')),
                ('processing_datetime', models.DateTimeField(blank=True, default=None, null=True, verbose_name='processing datetime')),
                ('error_datetime', models.DateTimeField(blank=True, default=None, null=True, verbose_name='error datetime')),
                ('completed_datetime', models.DateTimeField(blank=True, default=None, null=True, verbose_name='completed datetime')),
                ('player_id', models.CharField(max_length=50, verbose_name='PlayerId')),
                ('player_name', models.CharField(max_length=50, verbose_name='PlayerName')),
                ('xp', models.IntegerField(default=0, verbose_name='xp')),
                ('gem', models.IntegerField(default=0, verbose_name='gem')),
                ('gold', models.IntegerField(default=0, verbose_name='gold')),
                ('key', models.IntegerField(default=0, verbose_name='key')),
                ('level', models.IntegerField(default=0, verbose_name='level')),
                ('population', models.IntegerField(default=0, verbose_name='population')),
                ('warehouse', models.IntegerField(default=0, verbose_name='warehouse')),
                ('train_parts_common', models.IntegerField(default=0, verbose_name='train_common')),
                ('train_parts_rare', models.IntegerField(default=0, verbose_name='train_rare')),
                ('train_parts_epic', models.IntegerField(default=0, verbose_name='train_epic')),
                ('train_parts_legendary', models.IntegerField(default=0, verbose_name='train_legendary')),
                ('blue_city_plans', models.IntegerField(default=0, verbose_name='blue_city_plans')),
                ('yellow_city_plans', models.IntegerField(default=0, verbose_name='yellow_city_plans')),
                ('red_city_plans', models.IntegerField(default=0, verbose_name='red_city_plans')),
                ('dispatchers', models.IntegerField(default=0, verbose_name='dispatchers')),
                ('guild_dispatchers', models.IntegerField(default=0, verbose_name='guild_dispatchers')),
                ('next_event_datetime', models.DateTimeField(default=None, null=True, verbose_name='next event datetime')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created date')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='modified date')),
                ('article_amount', models.IntegerField(default=0, verbose_name='article_amount')),
                ('craft_time', models.IntegerField(default=0, verbose_name='craft_time')),
                ('article_ids', models.CharField(max_length=255, verbose_name='article_ids')),
                ('article_amounts', models.CharField(max_length=255, verbose_name='article_amounts')),
                ('level_req', models.IntegerField(default=0, verbose_name='level required')),
                ('level_from', models.IntegerField(default=0, verbose_name='level from')),
                ('article', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bot.article')),
                ('factory', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bot.factory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='PlayerJobReward',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created date')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='modified date')),
                ('value', models.IntegerField(default=0, verbose_name='value')),
                ('amount', models.IntegerField(default=0, verbose_name='amount')),
                ('article', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bot.article')),
                ('job', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bot.playerjob')),
            ],
            options={
                'verbose_name': 'Player Job Reward',
                'verbose_name_plural': 'Player Job Rewards',
            },
        ),
        migrations.CreateModel(
            name='PlayerJobRequirements',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created date')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='modified date')),
                ('type', models.CharField(max_length=50, verbose_name='requirement type')),
                ('value', models.IntegerField(verbose_name='requirement value')),
                ('job', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bot.playerjob')),
            ],
            options={
                'verbose_name': 'Player Job Requirement',
                'verbose_name_plural': 'Player Job Requirements',
            },
        ),
        migrations.CreateModel(
            name='PlayerJobRequiredArticle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created date')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='modified date')),
                ('amount', models.IntegerField(default=0, verbose_name='amount')),
                ('article', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bot.article')),
                ('job', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bot.playerjob')),
            ],
            options={
                'verbose_name': 'Player Job Required Article',
                'verbose_name_plural': 'Player Job Required Articles',
            },
        ),
        migrations.AddField(
            model_name='playerjob',
            name='version',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bot.runversion'),
        ),
        migrations.CreateModel(
            name='PlayerFactoryProductOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created date')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='modified date')),
                ('amount', models.IntegerField(default=0, verbose_name='amount')),
                ('craft_time', models.IntegerField(default=0, verbose_name='CraftTime')),
                ('finish_time', models.DateTimeField(default=None, null=True, verbose_name='FinishTime')),
                ('finishes_at', models.DateTimeField(default=None, null=True, verbose_name='FinishesAt')),
                ('article', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bot.article')),
                ('player_factory', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bot.playerfactory')),
                ('version', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bot.runversion')),
            ],
            options={
                'verbose_name': 'Player Factory Product Order',
                'verbose_name_plural': 'Player Factory Product Orders',
            },
        ),
        migrations.AddField(
            model_name='playerfactory',
            name='version',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bot.runversion'),
        ),
        migrations.CreateModel(
            name='PlayerDestination',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created date')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='modified date')),
                ('location_id', models.IntegerField(null=True, verbose_name='location_id')),
                ('definition_id', models.IntegerField(null=True, verbose_name='definition_id')),
                ('train_limit_count', models.IntegerField(null=True, verbose_name='train_limit_count')),
                ('train_limit_refresh_time', models.DateTimeField(null=True, verbose_name='train_limit_refresh_time')),
                ('train_limit_refresh_at', models.DateTimeField(null=True, verbose_name='train_limit_refresh_at')),
                ('multiplier', models.IntegerField(default='', max_length=255, null=True, verbose_name='multiplier')),
                ('version', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bot.runversion')),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
            },
        ),
        migrations.CreateModel(
            name='PlayerBuilding',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created date')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='modified date')),
                ('instance_id', models.IntegerField(null=True, verbose_name='instance id')),
                ('definition_id', models.IntegerField(null=True, verbose_name='instance id')),
                ('rotation', models.IntegerField(null=True, verbose_name='instance id')),
                ('level', models.IntegerField(null=True, verbose_name='instance id')),
                ('upgrade_task', models.CharField(default='', max_length=255, null=True, verbose_name='upgrade task')),
                ('version', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bot.runversion')),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created date')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='modified date')),
                ('sprite', models.CharField(max_length=255, null=True, verbose_name='sprite id')),
                ('time', models.IntegerField(default=0, verbose_name='time')),
                ('travel_duration', models.IntegerField(default=0, verbose_name='travel_duration')),
                ('multiplier', models.IntegerField(default=0, verbose_name='multiplier')),
                ('refresh_time', models.IntegerField(default=0, verbose_name='refresh_time')),
                ('train_limit', models.IntegerField(default=0, verbose_name='train_limit')),
                ('capacity', models.IntegerField(default=0, verbose_name='capacity')),
                ('requirements', models.CharField(max_length=255, verbose_name='requirements')),
                ('article', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bot.article')),
                ('location', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bot.location')),
                ('region', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bot.region')),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
            },
        ),
    ]
