# Generated by Django 4.1.4 on 2023-02-11 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runversion',
            name='now',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='now'),
        ),
    ]
