# Generated by Django 4.1.4 on 2023-04-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tsmilestone",
            name="rewards",
            field=models.CharField(default="", max_length=500, verbose_name="rewards"),
        ),
        migrations.AlterField(
            model_name="tsuserlevel",
            name="rewards",
            field=models.CharField(default="", max_length=500, verbose_name="rewards"),
        ),
    ]
