# Generated by Django 4.1.4 on 2023-03-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runversion',
            name='firebase_token',
            field=models.TextField(blank=True, default='', max_length=10240, verbose_name='firebase token'),
        ),
        migrations.AddField(
            model_name='runversion',
            name='firebase_uid',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='firebase uid'),
        ),
    ]
