# Generated by Django 4.1.4 on 2023-02-24 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCityLoopTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created date')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='modified date')),
                ('next_replace_at', models.DateTimeField(null=True, verbose_name='UpgradeTaskNextReplaceAt')),
                ('next_video_replace_at', models.DateTimeField(null=True, verbose_name='UpgradeTaskNextVideoReplaceAt')),
                ('version', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.runversion')),
            ],
            options={
                'verbose_name': 'CityLoop Task',
                'verbose_name_plural': 'CityLoop Task',
            },
        ),
        migrations.CreateModel(
            name='PlayerCityLoopParcel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created date')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='modified date')),
                ('parcel', models.IntegerField(default=0, verbose_name='parcel')),
                ('version', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.runversion')),
            ],
            options={
                'verbose_name': 'CityLoop Parcel',
                'verbose_name_plural': 'CityLoop Parcels',
            },
        ),
    ]
