# Generated by Django 4.1.4 on 2023-01-23 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_alter_tstrain_era'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCompetition',
            fields=[
                ('content_category', models.IntegerField(choices=[(1, '기본'), (2, '이벤트'), (3, '유니언')], default=0, verbose_name='content category')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created date')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='modified date')),
                ('type', models.CharField(default='', max_length=20, verbose_name='Type')),
                ('level_from', models.IntegerField(null=True, verbose_name='LevelFrom')),
                ('max_attendees', models.IntegerField(null=True, verbose_name='MaxAttendees')),
                ('competition_id', models.CharField(default='', max_length=50, verbose_name='CompetitionId')),
                ('rewards', models.CharField(default='', max_length=255, verbose_name='Rewards')),
                ('starts_at', models.DateTimeField(null=True, verbose_name='StartsAt')),
                ('enrolment_available_to', models.DateTimeField(null=True, verbose_name='EnrolmentAvailableTo')),
                ('finishes_at', models.DateTimeField(null=True, verbose_name='FinishesAt')),
                ('expires_at', models.DateTimeField(null=True, verbose_name='ExpiresAt')),
                ('activated_at', models.DateTimeField(null=True, verbose_name='ActivatedAt')),
                ('progress', models.CharField(default='', max_length=255, verbose_name='Progress')),
                ('presentation_data_id', models.IntegerField(null=True, verbose_name='PresentationDataId')),
                ('guild_data', models.CharField(default='', max_length=255, verbose_name='GuildData')),
                ('scope', models.CharField(default='', max_length=20, verbose_name='Scope')),
                ('version', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servers.runversion')),
            ],
            options={
                'verbose_name': 'Player Competition',
                'verbose_name_plural': 'Player Competitions',
            },
        ),
    ]
