# Generated by Django 4.1.4 on 2023-04-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0002_alter_playercompetition_rewards_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playercompetition",
            name="rewards",
            field=models.TextField(default="", max_length=1000, verbose_name="Rewards"),
        ),
    ]
