# Generated by Django 4.1.4 on 2023-04-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0003_alter_playercompetition_rewards"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playercompetition",
            name="progress",
            field=models.TextField(
                default="", max_length=1000, verbose_name="Progress"
            ),
        ),
    ]
